import Link from "next/link";

export const metadata = {
  title: "Terms of Service | FedResume",
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-white">
      <nav className="bg-white border-b border-navy-100">
        <div className="max-w-6xl mx-auto px-4 h-16 flex items-center">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-8 h-8 bg-navy-900 rounded-lg flex items-center justify-center">
              <span className="text-accent-400 font-bold text-sm">FR</span>
            </div>
            <span className="font-bold text-xl text-navy-900">
              Fed<span className="text-navy-500">Resume</span>
            </span>
          </Link>
        </div>
      </nav>

      <div className="max-w-3xl mx-auto px-4 py-16">
        <h1 className="text-3xl font-bold text-navy-900 mb-2">Terms of Service</h1>
        <p className="text-navy-400 mb-10">Last updated: March 14, 2026</p>

        <div className="prose prose-navy max-w-none space-y-8 text-navy-700 leading-relaxed">
          <section>
            <h2 className="text-xl font-bold text-navy-900 mb-3">Service Description</h2>
            <p>FedResume is an AI-powered tool that converts civilian resumes into federal resume format. The service is provided by Ceradon Systems LLC.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-navy-900 mb-3">Payment &amp; Delivery</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>Each conversion costs $9.99 (USD), charged as a one-time payment via Stripe</li>
              <li>Your converted resume is delivered immediately after payment in your browser</li>
              <li>Each payment entitles you to one (1) resume generation</li>
              <li>No refunds are offered after the resume has been generated and delivered</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-navy-900 mb-3">AI-Generated Content Disclaimer</h2>
            <p>The federal resume generated by FedResume is created using artificial intelligence. While we strive for accuracy and compliance with OPM standards:</p>
            <ul className="list-disc pl-6 space-y-1 mt-2">
              <li><strong>You are responsible for reviewing all content before submission</strong></li>
              <li>The AI may generate placeholder fields (marked [PLACEHOLDER]) that you must fill in</li>
              <li>We do not guarantee that using our service will result in a job offer or referral</li>
              <li>We do not fabricate experience, but the AI restructures and enhances the information you provide</li>
              <li>All dates, job titles, supervisor information, and other factual details should be verified by you before submission to USAJobs</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-navy-900 mb-3">Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 space-y-1 mt-2">
              <li>Use the service for fraudulent purposes or to misrepresent your qualifications</li>
              <li>Attempt to bypass payment or rate limiting mechanisms</li>
              <li>Submit content that violates any applicable laws</li>
              <li>Resell or redistribute the service</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-navy-900 mb-3">Limitation of Liability</h2>
            <p>FedResume and Ceradon Systems LLC are not liable for any damages arising from use of this service, including but not limited to: rejected job applications, inaccurate AI-generated content, or service interruptions. The service is provided &quot;as is&quot; without warranties of any kind.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-navy-900 mb-3">Intellectual Property</h2>
            <p>You retain full ownership of your resume content. The generated federal resume is yours to use as you see fit. We claim no rights over your input or output content.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-navy-900 mb-3">Changes to Terms</h2>
            <p>We may update these terms at any time. Continued use of the service constitutes acceptance of updated terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-navy-900 mb-3">Contact</h2>
            <p>
              Ceradon Systems LLC<br />
              Email: <a href="mailto:noah@ceradonsystems.com" className="text-accent-600 underline">noah@ceradonsystems.com</a>
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
